pipeline:
  name: Build_CI
  identifier: Build_CI
  projectIdentifier: nexus
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: sritest
        repoName: Harness-POC
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Primarycluster
              namespace: harness-deploy
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: GCRPlaypen
                    image: docker:dind
                    shell: Sh
                    command: |
                      while ! docker ps; do 
                      echo "docker not present"
                      done 
                      echo "docker ready to use"
              - step:
                  type: Run
                  name: Build and Push
                  identifier: Build_and_Push
                  spec:
                    connectorRef: GCRPlaypen
                    image: google/cloud-sdk:latest
                    shell: Sh
                    command: |-
                      echo <+secrets.getValue("GCPPlaypen")> | base64 -d > tmp.json
                      glcoud auth activate-service-account --key-file=tmp.json

                      gcloud auth configure-docker eu.gcr.io/playpen-r2tsls -q

                      docker build . -t eu.gcr.io/playpen-r2tsls/nodejs:latest

                      docker image push eu.gcr.io/playpen-r2tsls/nodejs:latest
          sharedPaths:
            - /var/run
            - /var/lib/docker
