pipeline:
  name: Deploy Build
  identifier: Build_CI
  projectIdentifier: nexus
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy to Primary
        identifier: Deploy_to_Primary
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: PythonAppGar
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: playpen
            deployToAll: false
            infrastructureDefinitions:
              - identifier: DevPrimary
                inputs:
                  identifier: DevPrimary
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
          execution:
            steps:
              - step:
                  type: K8sCanaryDeploy
                  name: App deployment to Primary Region
                  identifier: K8sCanaryDeploy_1
                  spec:
                    skipDryRun: false
                    instanceSelection:
                      type: Count
                      spec:
                        count: 1
                  timeout: 10m
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
