pipeline:
  name: Build_CI
  identifier: Build_CI
  projectIdentifier: nexus
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: sritest
        repoName: Harness-POC
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Primarycluster
              namespace: harness-deploy
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: GCRPlaypen
                    host: europe-docker.pkg.dev
                    projectID: playpen-r2tsls
                    imageName: harness/py-app
                    tags:
                      - <+pipeline.properties.ci.codebase.build.build.spec.number>
                    dockerfile: Dockerfile
                    context: BuildApp
          sharedPaths:
            - /var/run
            - /var/lib/docker
        variables: []
