apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}-svc
  labels:
    app: py-app
spec:
  type: {{ .Values.svctype }}
  ports:
  - port: {{ .Values.port }}
  selector:
    app: py-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: py-app
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date) 'Hello World'; sleep 10; done"]
