apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}-svc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.servicename }}-svc
