apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}-svc
  labels:
    app: nginx
spec:
  type: {{ .Values.svctype }}
  ports:
  - port: {{ .Values.port }}
  selector:
    app: nginx
---
