apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    chart: "{{ .Chart.Name }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
