pipeline:
  name: KubeDeploy
  identifier: KubeDeploy
  projectIdentifier: nexus
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: Deploy to Primary
            identifier: Deploy_to_Primary
            template:
              templateRef: DevPrimaryStage
              versionLabel: "1.0"
  variables:
    - name: HELM_REPO
      type: String
      description: ""
      value: <+input>
    - name: RELEASE_TAG
      type: String
      description: ""
      value: <+input>
